import "./App.css";
import React, { Component } from "react";
import Navbar from "./components/Navbar";
import News from "./components/News";
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import LoadingBar from "react-top-loading-bar";

//https://www.youtube.com/watch?v=De9z9n7PgzE
//https://github.com/chiragobhan/newsio
export default class App extends Component {
  state = {
    progress: 0,
    sidebarOpen: 1,
  };
  handleViewSidebar = () => {
    this.setState({ sidebarOpen: !this.state.sidebarOpen });
  };
  setProgress = (progress) => {
    this.setState({ progress: progress });
  };
  render() {
    return (
      <Router>
        <div>
          <Navbar
            sidebarOpen={this.state.sidebarOpen}
            handleViewSidebar={this.handleViewSidebar}
          />
          <LoadingBar
            height={3}
            color="#f11946"
            progress={this.state.progress}
          />
          {/* <Sidebar setSide={1} /> */}
          <Routes>
            <Route
              exact
              path="/News-Everyday2/"
              element={
                <News
                  setSide={this.state.sidebarOpen}
                  setProgress={this.setProgress}
                  key="general"
                  pageSize={22}
                  country="in"
                  category="general"
                />
              }
            />
            <Route
              exact
              path="/"
              element={
                <News
                  setSide={this.state.sidebarOpen}
                  setProgress={this.setProgress}
                  key="general"
                  pageSize={22}
                  country="in"
                  category="general"
                />
              }
            />
            <Route
              exact
              path="/business"
              element={
                <News
                  setSide={this.state.sidebarOpen}
                  setProgress={this.setProgress}
                  key="business"
                  pageSize={22}
                  country="in"
                  category="business"
                />
              }
            />
            <Route
              exact
              path="/entertainment"
              element={
                <News
                  setSide={this.state.sidebarOpen}
                  setProgress={this.setProgress}
                  key="entertainment"
                  pageSize={22}
                  country="in"
                  category="entertainment"
                />
              }
            />
            <Route
              exact
              path="/health"
              element={
                <News
                  setSide={this.state.sidebarOpen}
                  setProgress={this.setProgress}
                  key="health"
                  pageSize={22}
                  country="in"
                  category="health"
                />
              }
            />
            <Route
              exact
              path="/science"
              element={
                <News
                  setSide={this.state.sidebarOpen}
                  setProgress={this.setProgress}
                  key="science"
                  pageSize={22}
                  country="in"
                  category="science"
                />
              }
            />
            <Route
              exact
              path="/sports"
              element={
                <News
                  setSide={this.state.sidebarOpen}
                  setProgress={this.setProgress}
                  key="sports"
                  pageSize={22}
                  country="in"
                  category="sports"
                />
              }
            />
            <Route
              exact
              path="/technology"
              element={
                <News
                  setSide={this.state.sidebarOpen}
                  setProgress={this.setProgress}
                  key="technology"
                  pageSize={22}
                  country="in"
                  category="technology"
                />
              }
            />
            <Route
              exact
              path="/News18"
              element={
                <News
                  setSide={this.state.sidebarOpen}
                  setProgress={this.setProgress}
                  key="News18"
                  pageSize={22}
                  category="null"
                  query="News18"
                />
              }
            />
            <Route
              exact
              path="/bbc-news"
              element={
                <News
                  setSide={this.state.sidebarOpen}
                  setProgress={this.setProgress}
                  key="bbc-news"
                  pageSize={22}
                  category="null"
                  query="bbc-news"
                />
              }
            />
            <Route
              exact
              path="/business-insider"
              element={
                <News
                  setSide={this.state.sidebarOpen}
                  setProgress={this.setProgress}
                  key="business-insider"
                  pageSize={22}
                  category="null"
                  query="business-insider"
                />
              }
            />
            <Route
              exact
              path="/engadget"
              element={
                <News
                  setSide={this.state.sidebarOpen}
                  setProgress={this.setProgress}
                  key="engadget"
                  pageSize={22}
                  category="null"
                  query="engadget"
                />
              }
            />
            <Route
              exact
              path="/google-news"
              element={
                <News
                  setSide={this.state.sidebarOpen}
                  setProgress={this.setProgress}
                  key="google-news"
                  pageSize={22}
                  category="null"
                  query="google-news"
                />
              }
            />
            <Route
              exact
              path="/cnn"
              element={
                <News
                  setSide={this.state.sidebarOpen}
                  setProgress={this.setProgress}
                  key="cnn"
                  pageSize={22}
                  category="null"
                  query="cnn"
                />
              }
            />
            <Route
              exact
              path="/Hindustan-times"
              element={
                <News
                  setSide={this.state.sidebarOpen}
                  setProgress={this.setProgress}
                  key="Hindustan-times"
                  pageSize={22}
                  category="null"
                  query="Hindustan-times"
                />
              }
            />
            <Route
              exact
              path="/Moneycontrol"
              element={
                <News
                  setSide={this.state.sidebarOpen}
                  setProgress={this.setProgress}
                  key="Moneycontrol"
                  pageSize={22}
                  category="null"
                  query="Moneycontrol"
                />
              }
            />
            <Route
              exact
              path="/the-times-of-india"
              element={
                <News
                  setSide={this.state.sidebarOpen}
                  setProgress={this.setProgress}
                  key="the-times-of-india"
                  pageSize={22}
                  category="null"
                  query="the-times-of-india"
                />
              }
            />
            <Route
              exact
              path="/the-washington-post"
              element={
                <News
                  setSide={this.state.sidebarOpen}
                  setProgress={this.setProgress}
                  key="the-washington-post"
                  pageSize={22}
                  category="null"
                  query="the-washington-post"
                />
              }
            />
          </Routes>
        </div>
      </Router>
    );
  }
}
